### ISSUE TITLE
Multiple Sensor operability

### ISSUE THREAD

**Issue by deadeyesky** [nagimov/adxl345spi#5]
Is there a way to add multiple sensor support into the program and make it print in the format of 
`time, x1, y1, z1, x2, y2, z2`? I think it might have something to do with the chip select

**Comment by nagimov** [comment]
@deadeyesky you can open two handles `h1` and `h2` around [here](https://github.com/nagimov/adxl345spi/blob/90ee814de56cd5f7a40c570b9b100077df7b3261/adxl345spi.c#L134) and follow along reading from both of them.
See how to connect two accelerometers to SPI peripherals and open them via `spiOpen` [here](http://abyz.me.uk/rpi/pigpio/cif.html#spiOpen)
