### ISSUE TITLE
ADXL345SPI always return 0,0,0

### ISSUE THREAD

**Issue by JartX** [nagimov/adxl345spi#8]
sudo adxl345spi 
[sudo] password for pi: 
time = 0.000, x = 0.000, y = 0.000, z = 0.000
time = 0.201, x = 0.000, y = 0.000, z = 0.000
time = 0.401, x = 0.000, y = 0.000, z = 0.000
time = 0.602, x = 0.000, y = 0.000, z = 0.000
time = 0.803, x = 0.000, y = 0.000, z = 0.000
time = 1.004, x = 0.000, y = 0.000, z = 0.000
time = 1.205, x = 0.000, y = 0.000, z = 0.000
time = 1.405, x = 0.000, y = 0.000, z = 0.000
time = 1.606, x = 0.000, y = 0.000, z = 0.000
time = 1.807, x = 0.000, y = 0.000, z = 0.000
time = 2.008, x = 0.000, y = 0.000, z = 0.000
time = 2.209, x = 0.000, y = 0.000, z = 0.000
time = 2.410, x = 0.000, y = 0.000, z = 0.000
time = 2.611, x = 0.000, y = 0.000, z = 0.000
time = 2.812, x = 0.000, y = 0.000, z = 0.000
time = 3.013, x = 0.000, y = 0.000, z = 0.000
time = 3.214, x = 0.000, y = 0.000, z = 0.000
time = 3.415, x = 0.000, y = 0.000, z = 0.000
time = 3.616, x = 0.000, y = 0.000, z = 0.000
time = 3.817, x = 0.000, y = 0.000, z = 0.000
time = 4.017, x = 0.000, y = 0.000, z = 0.000
time = 4.218, x = 0.000, y = 0.000, z = 0.000
time = 4.419, x = 0.000, y = 0.000, z = 0.000
time = 4.620, x = 0.000, y = 0.000, z = 0.000
time = 4.821, x = 0.000, y = 0.000, z = 0.000

My system data:

RPI3B+
5.10.17-v7+ #1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l GNU/Linux
Debian Buster 

I have checked the continuity of the cables with a multimeter and it is correct. Any idea about this problem? Many thanks for your time

**Comment by nagimov** [comment]
@JartX how long is your cable? Have you tested it with shorter wires (jumper cables)?

**Comment by JartX** [comment]
> @JartX how long is your cable? Have you tested it with shorter wires (jumper cables)?
Yes, 20cm cable always Jumper cable. :(
![IMG_20210314_132809](https://user-images.githubusercontent.com/8399211/111068502-48d2ce80-84c9-11eb-9ade-eba1296eeb72.jpg)

lsmod: 
https://pastebin.com/icyjkCge

/boot/config.txt
https://pastebin.com/EDQMnmrF

**Comment by JartX** [comment]
![IMG_20210314_134209](https://user-images.githubusercontent.com/8399211/111069016-6143e880-84cb-11eb-8080-8c510c25bcc8.jpg)
![IMG_20210314_134204](https://user-images.githubusercontent.com/8399211/111069023-65700600-84cb-11eb-9a58-f2d80e741bfe.jpg)
![IMG_20210314_134156](https://user-images.githubusercontent.com/8399211/111069031-69038d00-84cb-11eb-8ec8-423e4fa3adea.jpg)

**Comment by JartX** [comment]
SPI TEST: https://www.raspberrypi.org/documentation/hardware/raspberrypi/spi/README.md
/spidev_test -D /dev/spidev0.0
spi mode: 4
bits per word: 8
max speed: 500000 Hz (500 KHz)

00 00 00 00 00 00 
00 00 00 00 00 00 
00 00 00 00 00 00 
00 00 00 00 00 00 
00 00 00 00 00 00 
00 00 00 00 00 00 
00 00 
pi@fluiddpi:~ $ ./spidev_test -D /dev/spidev0.1
spi mode: 4
bits per word: 8
max speed: 500000 Hz (500 KHz)

00 00 00 00 00 00 
00 00 00 00 00 00 
00 00 00 00 00 00 
00 00 00 00 00 00 
00 00 00 00 00 00 
00 00 00 00 00 00 
00 00 

GPIO TEST:
Skipped non-user gpios: 0 1 28 29 30 31 
Tested user gpios: 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 
Failed user gpios: None
It can be a problem with the driver of the spi?

UPDATE: Second pi3b+ same problem.

**Comment by nagimov** [comment]
@JartX yes this looks like an SPI issue
Could you run the same test using this raspbian image: https://downloads.raspberrypi.org/raspbian_full/images/raspbian_full-2020-02-14/2020-02-13-raspbian-buster-full.zip

**Comment by JartX** [comment]
Not work :S 
Any adxl345 spi work :(
https://www.amazon.es/gp/product/B07TW27BS5/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1
https://www.amazon.es/gp/product/B07DMZCGP9/ref=ppx_yo_dt_b_asin_title_o05_s00?ie=UTF8&psc=1

**Comment by JartX** [comment]
![image](https://user-images.githubusercontent.com/8399211/111195936-11dde500-85bd-11eb-8687-6a3d6db83fa4.png)

Working! This module has been assembled to work only on I2C MODE, to work on SPI you need to desolder the "R4"
