### ISSUE TITLE
Package 'pigpio' has no installation candidate

### ISSUE THREAD

**Issue by Deneteus** [nagimov/adxl345spi#9]
I have PIGPIOD installed but it's giving an error about no installation candidate.

![image](https://user-images.githubusercontent.com/6380390/115977493-6a9a8900-a53e-11eb-91a3-cd2d2d6871c2.png)

I am trying to get this setup on an RPI3.

**Comment by Deneteus** [comment]
After much wrangling I was able to get it to work after a reboot. 
![image](https://user-images.githubusercontent.com/6380390/115977939-f19d3080-a541-11eb-8024-004c9bf9beeb.png)

**Comment by nagimov** [comment]
This looks like an apt issue to me. Unfortunately I am not familiar with the octopi and its tweaks and differences from raspbian.

**Comment by Deneteus** [comment]
> This looks like an apt issue to me. Unfortunately I am not familiar with the octopi and its tweaks and differences from raspbian.

That is Raspbian. 

![image](https://user-images.githubusercontent.com/6380390/116429958-001e6d00-a80c-11eb-900a-1b3109050c2c.png)

**Comment by nagimov** [comment]
Yes octopi is based on raspbian, but it's tweaked and repackaged via [CustomPiOS](https://github.com/guysoft/CustomPiOS). Sorry I don't have the resources to test against multiple distributions.
If you have issues with adxl on octopi, I would recommend running octoprint on standard raspbian, e.g. via docker (there are octpprint images compiled for arm).

**Comment by Deneteus** [comment]
I am way ahead of you. I already setup a PI with the stock Raspbian image to test it there when I made the post. I'll let you know if I find a solution. It looks like it may be an environment path issue to me but I haven't had time to test further.

**Comment by Turbine1991** [comment]
> Yes octopi is based on raspbian, but it's tweaked and repackaged via [CustomPiOS](https://github.com/guysoft/CustomPiOS). Sorry I don't have the resources to test against multiple distributions. If you have issues with adxl on octopi, I would recommend running octoprint on standard raspbian, e.g. via docker (there are octpprint images compiled for arm).

Same issue with Armbian Ubuntu.

Solution:
```
git clone https://github.com/joan2937/pigpio.git && cd pigpio
sudo make install
```

But there's other bugs with adxl345spi, it needs an update too.

```
dxl345spi.c: In function ‘printUsage’:
adxl345spi.c:28:34: warning: ‘%s’ directive argument is not a nul-terminated string [-Wformat-overflow=]
```
```
+---------------------------------------------------------+
|Sorry, this system does not appear to be a raspberry pi. |
|aborting.                                                |
+---------------------------------------------------------+
```

Seriously.. that's why we have WiringPI for our various boards.
